@if($slideOneTitles)

    <div class="ls-slide" data-ls="bgcolor:#000000;kenburnssca5le:1.2;parallaxtype:3d;parallaxaxis:x;parallaxrotate:-10;">
        <div style="top:0px;left:0px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;width:100%;height:100%;opacity:1;background:#ffffff;" class="ls-l" data-ls="showinfo:1;offsetyin:-100%;fadein:false;offsetxout:-100sw;durationout:1;startatout:transitioninend + 5000;easingout:easeInExpo;fadeout:false;position:fixed;"></div>
        <div style="background: rgba(0,0,0,1); background: -moz-linear-gradient(top, rgba(0,0,0,1) 0%, rgba(92,107,63,1) 100%); background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(0,0,0,1)), color-stop(100%, rgba(92,107,63,1))); background: -webkit-linear-gradient(top, rgba(0,0,0,1) 0%, rgba(92,107,63,1) 100%); background: -o-linear-gradient(top, rgba(0,0,0,1) 0%, rgba(92,107,63,1) 100%); background: -ms-linear-gradient(top, rgba(0,0,0,1) 0%, rgba(92,107,63,1) 100%); background: linear-gradient(to bottom, rgba(0,0,0,1) 0%, rgba(92,107,63,1) 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#000000', endColorstr='#5c6b3f', GradientType=0 );top:0px;left:0px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;width:100%;height:100%;opacity:1;" class="ls-l" data-ls="showinfo:1;offsetyin:-100%;delayin:4600;fadein:false;offsetxout:-100sw;easingout:easeInExpo;fadeout:false;position:fixed;"></div>
        <div style="background: rgba(0,0,0,.5);top:0px;left:0px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;width:100%;height:100%;opacity:1;" class="ls-l" data-ls="showinfo:1;offsetyin:-100%;delayin:4600;fadein:false;offsetxout:-100sw;easingout:easeInExpo;fadeout:false;position:fixed;"></div>
        <p style="top:40%;left:50%;text-align:initial;font-weight:300;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:75px;color:#333333;" class="ls-l" data-ls="showinfo:1;offsetyin:-50%;durationin:1500;delayin:500;easingin:easeOutQuint;rotatexin:60;scalexin:.65;scaleyin:.8;texttransitionout:true;texttypeout:chars_asc;textshiftout:25;textdurationout:600;textstartatout:allinend - 500;textrotatexout:90;texttransformoriginout:50% 50% 30px;">{{$slideOneTitles[0]['attributes']['title1'.$Language]}}</p>
        <p style="top:40%;left:50%;text-align:initial;font-weight:300;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:75px;color:#333333;" class="ls-l" data-ls="showinfo:1;transitionin:false;texttransitionin:true;texttypein:chars_asc;textshiftin:25;textdurationin:600;textstartatin:transitioninstart + 1400;textrotatexin:-90;texttransformoriginin:50% 50% 30px;texttransitionout:true;texttypeout:chars_asc;textshiftout:25;textdurationout:600;textstartatout:textinend + 500;textrotatexout:90;texttransformoriginout:50% 50% 30px;">{{$slideOneTitles[0]['attributes']['title2'.$Language]}}</p>
        <p style="top:55%;left:50%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Lato;color:rgba(232, 31, 0, 0.93);font-size:490px;height:370px;line-height:340px;" class="ls-l" data-ls="showinfo:1;offsetyin:-100lh;durationin:1200;delayin:2000;easingin:easeOutQuint;clipin:100% 0 0 0;offsetyout:20sh;startatout:transitioninend + 800;easingout:easeInQuint;scalexout:.5;scaleyout:2;transformoriginout:50% -50% 0;">{{$slideOneTitles[0]['attributes']['title3'.$Language]}}</p>
        <p style="left:50%;text-align:initial;font-weight:300;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:60px;color:#333333;top:70%;height:55px;line-height:45px;" class="ls-l" data-ls="showinfo:1;offsetyin:-100lh;durationin:1200;delayin:2500;easingin:easeOutQuint;clipin:100% 0 0 0;startatout:slidechangeonly + 0;texttransitionout:true;texttypeout:chars_center;textoffsetyout:10sh;textdurationout:750;texteasingout:easeInQuint;textrotateout:0|-5|5|-10|10|-15|15;textscaleyout:4;texttransformoriginout:50% 0% 0;">{{$slideOneTitles[0]['attributes']['title4'.$Language]}}</p>


        @if($images)

            <?php

            $photo1 = DB::table('photos')->where('id','=',$images[0]['attributes']['photo_id'])->first();
            $photo2 = DB::table('photos')->where('id','=',$images[1]['attributes']['photo_id'])->first();
            $photo3 = DB::table('photos')->where('id','=',$images[2]['attributes']['photo_id'])->first();
            $photo4 = DB::table('photos')->where('id','=',$images[3]['attributes']['photo_id'])->first();
            $photo5 = DB::table('photos')->where('id','=',$images[4]['attributes']['photo_id'])->first();
            $photo6 = DB::table('photos')->where('id','=',$images[5]['attributes']['photo_id'])->first();
            $photo7 = DB::table('photos')->where('id','=',$images[6]['attributes']['photo_id'])->first();
            $photo8 = DB::table('photos')->where('id','=',$images[7]['attributes']['photo_id'])->first();
            $photo9 = DB::table('photos')->where('id','=',$images[8]['attributes']['photo_id'])->first();
            ?>

            <img width="600" height="338" src="{{asset('uploads/' . $photo1->file)}} " class="ls-l" alt=""  srcset= "{{asset('uploads/' . $photo1->file)}}"  600w, {{asset('uploads/' . $photo1->file)}} 300w" sizes="(max-width: 600px) 100vw, 600px" style="box-shadow: 0 10px 30px rgba(0,0,0,.4);top:-20%;left:90%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;border-radius:10px;style:box-shadow: 0 10px 30px rgba(0,0,0,.4);;" data-ls="showinfo:1;durationin:0;delayin:2000;offsetxout:-30sw;easingout:easeInBack;rotateout:-2;skewxout:9;loop:true;loopoffsety:140sh;loopduration:12250;loopstartat:allinend + 5000;looprotate:random(-60,60);loopcount:-1;looptransformperspective:2000;parallax:true;parallaxlevel:10;position:fixed;">
            <img width="600" height="338" src="{{asset('uploads/' . $photo2->file)}} " class="ls-l" alt=""  srcset= "{{asset('uploads/' . $photo2->file)}}"  600w, {{asset('uploads/' . $photo2->file)}} 300w" sizes="(max-width: 600px) 100vw, 600px" style="box-shadow: 0 10px 30px rgba(0,0,0,.4);top:-20%;left:90%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;border-radius:10px;style:box-shadow: 0 10px 30px rgba(0,0,0,.4);;" data-ls="showinfo:1;durationin:0;delayin:2000;offsetxout:-30sw;easingout:easeInBack;rotateout:-2;skewxout:9;loop:true;loopoffsety:140sh;loopduration:12250;loopstartat:allinend + 5000;looprotate:random(-60,60);loopcount:-1;looptransformperspective:2000;parallax:true;parallaxlevel:10;position:fixed;">
            <img width="600" height="338" src="{{asset('uploads/' . $photo3->file)}} " class="ls-l" alt="" srcset=  "{{asset('uploads/' . $photo3->file)}}"  600w, {{asset('uploads/' . $photo3->file)}} 300w" sizes="(max-width: 600px) 100vw, 600px" style="box-shadow: 0 10px 30px rgba(0,0,0,.4);top:-20%;left:20%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;border-radius:10px;style:box-shadow: 0 10px 30px rgba(0,0,0,.4);;" data-ls="showinfo:1;durationin:0;delayin:2000;offsetxout:-40sw;easingout:easeInBack;rotateout:-2;skewxout:12;loop:true;loopoffsety:140sh;loopduration:12500;loopstartat:allinend + 2000;looprotate:random(-60,60);loopcount:-1;looptransformperspective:2000;parallax:true;parallaxlevel:15;position:fixed;">
            <img width="600" height="338" src="{{asset('uploads/' . $photo4->file)}} " class="ls-l" alt="" srcset=  "{{asset('uploads/' . $photo4->file)}}"  600w, {{asset('uploads/' . $photo4->file)}} 300w" sizes="(max-width: 600px) 100vw, 600px" style="box-shadow: 0 10px 30px rgba(0,0,0,.4);top:-20%;left:80%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;border-radius:10px;style:box-shadow: 0 10px 30px rgba(0,0,0,.4);;" data-ls="showinfo:1;durationin:0;delayin:2000;offsetxout:-50sw;easingout:easeInBack;rotateout:-3;skewxout:15;loop:true;loopoffsety:140sh;loopduration:13750;loopstartat:allinend + 1000;looprotate:random(-60,60);loopcount:-1;looptransformperspective:2000;parallax:true;parallaxlevel:15;position:fixed;">
            <img width="600" height="338" src="{{asset('uploads/' . $photo5->file)}} " class="ls-l" alt="" srcset=  "{{asset('uploads/' . $photo5->file)}}"  600w, {{asset('uploads/' . $photo5->file)}} 300w" sizes="(max-width: 600px) 100vw, 600px" style="box-shadow: 0 10px 30px rgba(0,0,0,.4);top:-20%;left:30%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;border-radius:10px;style:box-shadow: 0 10px 30px rgba(0,0,0,.4);;" data-ls="showinfo:1;durationin:0;delayin:2000;offsetxout:-60sw;easingout:easeInBack;rotateout:-3;skewxout:18;loop:true;loopoffsety:140sh;loopduration:14000;loopstartat:allinend + 8000;looprotate:random(-60,60);loopcount:-1;looptransformperspective:2000;parallax:true;parallaxlevel:20;position:fixed;">
            <img width="600" height="338" src="{{asset('uploads/' . $photo6->file)}} " class="ls-l" alt="" srcset=  "{{asset('uploads/' . $photo6->file)}}"  600w, {{asset('uploads/' . $photo6->file)}} 300w" sizes="(max-width: 600px) 100vw, 600px" style="box-shadow: 0 10px 30px rgba(0,0,0,.4);top:-20%;left:70%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;border-radius:10px;style:box-shadow: 0 10px 30px rgba(0,0,0,.4);;" data-ls="showinfo:1;durationin:0;delayin:2000;offsetxout:-70sw;easingout:easeInBack;rotateout:-4;skewxout:21;loop:true;loopoffsety:140sh;loopduration:13250;loopstartat:allinend + 3000;looprotate:random(-60,60);loopcount:-1;looptransformperspective:2000;parallax:true;parallaxlevel:20;position:fixed;">
            <img width="600" height="338" src="{{asset('uploads/' . $photo7->file)}} " class="ls-l" alt="" srcset=  "{{asset('uploads/' . $photo7->file)}}"  600w, {{asset('uploads/' . $photo7->file)}} 300w" sizes="(max-width: 600px) 100vw, 600px" style="box-shadow: 0 10px 30px rgba(0,0,0,.4);top:-20%;left:40%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;border-radius:10px;style:box-shadow: 0 10px 30px rgba(0,0,0,.4);;" data-ls="showinfo:1;durationin:0;delayin:2000;offsetxout:-80sw;easingout:easeInBack;rotateout:-4;skewxout:24;loop:true;loopoffsety:140sh;loopduration:13500;loopstartat:allinend + 6000;looprotate:random(-60,60);loopcount:-1;looptransformperspective:2000;parallax:true;parallaxlevel:25;position:fixed;">
            <img width="600" height="338" src="{{asset('uploads/' . $photo8->file)}} " class="ls-l" alt="" srcset=  "{{asset('uploads/' . $photo8->file)}}"  600w, {{asset('uploads/' . $photo8->file)}} 300w" sizes="(max-width: 600px) 100vw, 600px" style="box-shadow: 0 10px 30px rgba(0,0,0,.4);top:-20%;left:60%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;border-radius:10px;style:box-shadow: 0 10px 30px rgba(0,0,0,.4);;" data-ls="showinfo:1;durationin:0;delayin:2000;offsetxout:-90sw;easingout:easeInBack;rotateout:-5;skewxout:27;loop:true;loopoffsety:140sh;loopduration:12000;loopstartat:allinend + 7000;looprotate:random(-60,60);loopcount:-1;looptransformperspective:2000;parallax:true;parallaxlevel:25;position:fixed;">
            <img width="600" height="338" src="{{asset('uploads/' . $photo9->file)}} " class="ls-l" alt="" srcset=  "{{asset('uploads/' . $photo9->file)}}"  600w, {{asset('uploads/' . $photo9->file)}} 300w" sizes="(max-width: 600px) 100vw, 600px" style="box-shadow: 0 10px 30px rgba(0,0,0,.4);top:-20%;left:50%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;border-radius:10px;style:box-shadow: 0 0 50px rgba(0,0,0,.2);;" data-ls="showinfo:1;durationin:0;delayin:2000;offsetxout:-100sw;easingout:easeInBack;rotateout:-5;skewxout:30;loop:true;loopoffsety:140sh;loopduration:13000;loopstartat:allinend + 0;looprotate:random(-60,60);loopcount:-1;looptransformperspective:2000;parallax:true;parallaxlevel:30;position:fixed;">

        @endif



        <div style="background: -moz-linear-gradient(left, rgba(0,0,0,1) 0%, rgba(0,0,0,0) 40%, rgba(0,0,0,0) 60%, rgba(0,0,0,1) 100%); background: -webkit-linear-gradient(left, rgba(0,0,0,1) 0%,rgba(0,0,0,0) 40%,rgba(0,0,0,0) 60%,rgba(0,0,0,1) 100%); background: linear-gradient(to right, rgba(0,0,0,1) 0%,rgba(0,0,0,0) 40%,rgba(0,0,0,0) 60%,rgba(0,0,0,1) 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#000000', endColorstr='#000000',GradientType=1 ); ;top:0px;left:0px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;width:100%;height:100%;" class="ls-l" data-ls="showinfo:1;offsetyin:-100%;delayin:4600;fadein:false;offsetxout:-100sw;easingout:easeInExpo;fadeout:false;texttransitionin:true;texttypein:chars_asc;position:fixed;"></div>
        <div style="top:500px;left:250px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;height:500px;background:rgba(255,255,255,.9);;border-radius:5px;width:1000px;" class="ls-l" data-ls="showinfo:1;offsetyin:-120lh;delayin:5000;rotatexin:10;clipin:100% 0 0 0;startatout:slidechangeonly + 0;parallax:true;parallaxlevel:-26;parallaxtype:2d;parallaxevent:scroll;parallaxaxis:both;"></div>
        <p style="top:564px;left:50%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;color:#eb6713;font-size:75px;" class="ls-l" data-ls="showinfo:1;transitionin:false;texttransitionin:true;texttypein:words_center;textoffsetxin:0|-100|100;textstartatin:transitioninend + 5600;textrotateyin:0|-50|50;textscalexin:0|1|1;textscaleyin:0|1|1;parallax:true;parallaxlevel:-26;parallaxtype:2d;parallaxevent:scroll;parallaxaxis:both;">{{$slideOneTitles[0]['attributes']['title5'.$Language]}}</p>
        <p style="letter-spacing: -1px;top:655px;left:50%;text-align:initial;font-weight:300;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;color:#555555;font-size:40px;" class="ls-l" data-ls="showinfo:1;offsetyin:-100lh;delayin:6000;fadein:false;rotatexin:90;clipin:100% 0 0 0;parallax:true;parallaxlevel:-26;parallaxtype:2d;parallaxevent:scroll;parallaxaxis:both;">{{$slideOneTitles[0]['attributes']['title6'.$Language]}}</p>
        <p style="letter-spacing: -1px;top:750px;left:50%;text-align:initial;font-weight:300;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;color:#333;font-size:40px;" class="ls-l" data-ls="showinfo:1;offsetyin:-100lh;delayin:6200;fadein:false;rotatexin:90;clipin:100% 0 0 0;parallax:true;parallaxlevel:-26;parallaxtype:2d;parallaxevent:scroll;parallaxaxis:both;">{{$slideOneTitles[0]['attributes']['title7'.$Language]}}</p>
        <a style="" class="ls-l" href="#next" target="_self" data-ls="showinfo:1;offsetyin:-50lh;durationin:1500;delayin:6400;rotatexin:30;hover:true;hoveropacity:1;hoverscalex:1.05;hoverscaley:1.05;parallax:true;parallaxlevel:-26;parallaxtype:2d;parallaxevent:scroll;parallaxaxis:both;">
            <p style="top:840px;left:50%;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:36px;color:#ffffff;background:rgb(48, 152, 171);border-radius:50px;padding-top:10px;padding-bottom:10px;padding-right:40px;padding-left:40px;" class="">{{ $slideOneTitles[0]['attributes']['title8'.$Language]}}</p>
        </a>

        @endif

    </div>


