
@if($titles)
    @foreach($titles as $title)

<div class="ls-slide" data-ls="bgcolor:#000000;timeshift:-1000;kenburnsscale:1.2;">
    <div style="background: rgb(69,58,117); background: -moz-linear-gradient(top, rgba(69,58,117,1) 0%, rgba(0,0,0,1) 100%); background: -webkit-linear-gradient(top, rgba(69,58,117,1) 0%,rgba(0,0,0,1) 100%); background: linear-gradient(to bottom, rgba(69,58,117,1) 0%,rgba(0,0,0,1) 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#453a75', endColorstr='#000000',GradientType=0 ); ;top:0px;left:0px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;width:100%;height:100%;opacity:1;" class="ls-l" data-ls="showinfo:1;position:fixed;"></div>
    <div style="background: -moz-linear-gradient(left, rgba(0,0,0,1) 0%, rgba(0,0,0,0) 48%, rgba(0,0,0,0) 52%, rgba(0,0,0,1) 100%); background: -webkit-linear-gradient(left, rgba(0,0,0,1) 0%,rgba(0,0,0,0) 48%,rgba(0,0,0,0) 52%,rgba(0,0,0,1) 100%); background: linear-gradient(to right, rgba(0,0,0,1) 0%,rgba(0,0,0,0) 48%,rgba(0,0,0,0) 52%,rgba(0,0,0,1) 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#000000', endColorstr='#000000',GradientType=1 ); ;top:0px;left:-1px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;width:100%;height:100%;" class="ls-l" data-ls="showinfo:1;position:fixed;"></div>
    <img width="820" height="1000" src="{{asset('assets/img/computer.png')}}" class="ls-l" alt="" srcset="{{asset('assets/img/computer.png')}} 820w, {{asset('assets/img/computer.png')}} 246w,{{asset('assets/img/computer.png')}} 768w" sizes="(max-width: 820px) 100vw, 820px" style="left:630px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;top:250px;" data-ls="showinfo:1;offsetxin:right;delayin:500;easingin:easeOutBack;skewxin:-25;offsetxout:left;easingout:easeInBack;skewxout:25;">
    <p style="top:361px;left:259px;text-align:initial;font-weight:400;font-style:italic;text-decoration:none;wordwrap:false;opacity:1;color:#ccd3f5;font-size:40px;font-family:Handlee;" class="ls-l" data-ls="showinfo:1;transitionin:false;startatout:slidechangeonly + 1000;filterout:brightness(200%);texttransitionin:true;texttypein:chars_asc;textshiftin:25;textdurationin:750;textstartatin:transitioninend + 1000;rotation:-2;">{{$titles[0]['attributes']['title3'.$Language]}}</p>
    <p style="box-shadow: 0 5px 50px rgba(0,0,0,.05); border-top-left-radius: 5px; border-bottom-left-radius: 5px;top:436px;left:50px;text-align:right;font-weight:600;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:36px;color:#eeeeee;width:184px;padding-right:20px;padding-left:20px;background:rgba(86, 108, 199, 0.67);height:70px;line-height:70px;" class="ls-l" data-ls="showinfo:1;durationin:750;delayin:1500;easingin:easeOutBack;rotateyin:-90;transformoriginin:100% 50% 0;scalexout:.5;scaleyout:0;transformoriginout:0% 0% 0;">{{$titles[0]['attributes']['title4a'.$Language]}}</p>
    <p style="box-shadow: 0 5px 50px rgba(0,0,0,.05); border-top-right-radius: 5px; border-bottom-right-radius: 5px;top:436px;left:274px;text-align:initial;font-weight:600;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:36px;color:#eeeeee;width:240px;padding-right:20px;padding-left:20px;background:rgba(168, 84, 199, 0.67);height:70px;line-height:70px;" class="ls-l" data-ls="showinfo:1;durationin:750;delayin:1500;easingin:easeOutBack;rotateyin:90;transformoriginin:0% 50% 0;scalexout:.5;scaleyout:0;transformoriginout:-80% 0% 0;">{{$titles[0]['attributes']['title4b'.$Language]}}</p>
    <p style="white-space: normal;top:200px;left:62px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:true;opacity:1;font-family:Nunito;color:rgba(255,255,255,.9);;font-size:64px;padding-right:0px;width:600px;" class="ls-l" data-ls="showinfo:1;durationin:1;delayin:500;clipin:100% 0 0 0;offsetyout:-200lh;texttransitionin:true;texttypein:words_asc;textshiftin:100;textoffsetyin:-100lh;texteasingin:easeOutBack;textstartatin:transitioninstart + 0;">{{$titles[0]['attributes']['title1'.$Language]}}</p>
    <p style="white-space: normal;top:274px;left:70px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:true;opacity:1;font-family:Nunito;color:#8392d4;padding-right:0px;font-size:54px;width:600px;" class="ls-l" data-ls="showinfo:1;durationin:1;delayin:500;clipin:100% 0 0 0;offsetyout:-100lh;texttransitionin:true;texttypein:words_desc;textshiftin:100;textoffsetyin:100lh;texteasingin:easeOutBack;textstartatin:transitioninstart + 0;">{{$titles[0]['attributes']['title2'.$Language]}}</p>
    <p style="white-space: normal;top:650px;left:74px;text-align:left;font-weight:400;font-style:normal;text-decoration:none;wordwrap:true;opacity:1;font-family:Nunito;color:rgb(48, 152, 171);width:450px;font-size:30px;" class="ls-l" data-ls="showinfo:1;delayin:3500;clipin:0 0 0 100%;scalexout:.5;scaleyout:0;transformoriginout:0% 100% 0;texttransitionin:true;texttypein:lines_asc;textshiftin:30;textoffsetyin:-30;textstartatin:transitioninend - 700;">{{$titles[0]['attributes']['body'.$Language]}}</p>
    <a style="" class="ls-l" href="#next" target="_self" data-ls="showinfo:1;durationin:2000;delayin:4000;rotatexin:60;scalexin:.8;scaleyin:.8;rotatexout:60;scalexout:.8;scaleyout:.8;loop:true;loopoffsetx:15;loopduration:800;loopeasing:easeInQuint;loopcount:-1;loopyoyo:true;hover:true;hoveropacity:1;hoverscalex:1.05;hoverscaley:1.05;">
        <p style="top:1257px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:36px;color:#ffffff;background:rgba(255, 33, 48, 0.67);border-radius:50px;padding-top:10px;padding-bottom:10px;padding-right:40px;padding-left:40px;left:50px;" class="">NEXT SLIDE</p>
    </a><img width="820" height="1000" src="{{asset('assets/img/window.png')}}" class="ls-l" alt="" srcset="{{asset('assets/img/window.png')}} 820w, {{asset('assets/img/window.png')}} 246w, {{asset('assets/img/window.png')}} 768w" sizes="(max-width: 820px) 100vw, 820px" style="top:250px;left:630px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;" data-ls="showinfo:1;offsetxin:-80%;delayin:1500;easingin:easeOutCubic;rotatein:-15;scalexin:1.15;scaleyin:.9;transformoriginin:0% 100% 0;offsetxout:left;easingout:easeInBack;skewxout:25;">
    <img width="820" height="1000" src="{{asset('assets/img/editor-new.png')}}" class="ls-l" alt="" srcset="{{asset('assets/img/editor-new.png')}} 820w, {{asset('assets/img/editor-new.png')}} 246w, {{asset('assets/img/editor-new.png')}} 768w" sizes="(max-width: 820px) 100vw, 820px" style="top:250px;left:630px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;" data-ls="showinfo:1;offsetxin:-80%;delayin:1700;easingin:easeOutCubic;rotatein:-15;scalexin:1.15;scaleyin:.9;transformoriginin:0% 100% 0;offsetxout:left;easingout:easeInBack;skewxout:25;">
    <img width="820" height="1000" src="{{asset('assets/img/welcome.png')}}" class="ls-l" alt="" srcset="{{asset('assets/img/welcome.png')}} 820w, {{asset('assets/img/welcome.png')}} 246w, {{asset('assets/img/welcome.png')}} 768w" sizes="(max-width: 820px) 100vw, 820px" style="top:240px;left:630px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;" data-ls="showinfo:1;offsetxin:-80%;delayin:2100;easingin:easeOutCubic;rotatein:-15;scalexin:1.15;scaleyin:.9;transformoriginin:0% 100% 0;offsetxout:left;easingout:easeInBack;skewxout:25;loop:true;loopoffsetx:7;loopoffsety:-50;loopstartat:allinend + 500;loopeasing:easeInOutQuint;loopopacity:.3;loopcount:-1;loopyoyo:true;">
    <img width="820" height="1000" src="{{asset('assets/img/popout.png')}}" class="ls-l" alt="" srcset="{{asset('assets/img/popout.png')}} 820w, {{asset('assets/img/popout.png')}} 246w, {{asset('assets/img/popout.png')}} 768w" sizes="(max-width: 820px) 100vw, 820px" style="top:250px;left:630px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;" data-ls="showinfo:1;offsetxin:-80%;delayin:1900;easingin:easeOutCubic;rotatein:-15;scalexin:1.15;scaleyin:.9;transformoriginin:0% 100% 0;offsetxout:left;easingout:easeInBack;skewxout:25;loop:true;loopoffsetx:14;loopoffsety:-100;loopeasing:easeInOutQuint;loopskewy:-2;loopcount:1;">
    <div style="text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:.5;background:#ffffff;width:100px;height:100px;border-radius:100px;top:644px;left:862px;" class="ls-l" data-ls="showinfo:1;durationin:250;delayin:3600;easingin:linear;fadein:false;rotatein:-10;rotatexin:20;rotateyin:-30;scalexin:0;scaleyin:0;durationout:250;startatout:transitioninend + 0;easingout:linear;rotateout:-10;rotatexout:20;rotateyout:-30;scalexout:2;scaleyout:2;rotation:-10;rotationX:20;rotationY:-30;"></div>

@endforeach
    @endif
</div>
