<div class="ls-slide" data-ls="bgposition:50% 0%;bgcolor:#000000;transition2d:5;kenburnsscale:1.2;">
    @if($pics)
        <?php

        $photo1 = DB::table('photos')->where('id','=',$pics[0]['attributes']['photo_id'])->first();
        $photo2 = DB::table('photos')->where('id','=',$pics[1]['attributes']['photo_id'])->first();
        $photo3 = DB::table('photos')->where('id','=',$pics[2]['attributes']['photo_id'])->first();
        $photo4 = DB::table('photos')->where('id','=',$pics[3]['attributes']['photo_id'])->first();
        $photo5 = DB::table('photos')->where('id','=',$pics[4]['attributes']['photo_id'])->first();
        $photo6 = DB::table('photos')->where('id','=',$pics[5]['attributes']['photo_id'])->first();
        $photo7 = DB::table('photos')->where('id','=',$pics[6]['attributes']['photo_id'])->first();
        $photo8 = DB::table('photos')->where('id','=',$pics[7]['attributes']['photo_id'])->first();
        $photo9 = DB::table('photos')->where('id','=',$pics[8]['attributes']['photo_id'])->first();
        $photo10 = DB::table('photos')->where('id','=',$pics[9]['attributes']['photo_id'])->first();
        $photo11 = DB::table('photos')->where('id','=',$pics[10]['attributes']['photo_id'])->first();
        $photo12 = DB::table('photos')->where('id','=',$pics[11]['attributes']['photo_id'])->first();
        $photo13 = DB::table('photos')->where('id','=',$pics[12]['attributes']['photo_id'])->first();
        ?>

    <img width="1500" height="1500" src="{{asset('uploads/' . $photo1->file)}}" class="ls-bg" alt=""srcset="{{asset('uploads/' . $photo1->file)}} 1500w, {{asset('uploads/' . $photo1->file)}} 150w, {{asset('uploads/' . $photo1->file)}} 300w, {{asset('uploads/' . $photo1->file)}} 768w, {{asset('uploads/' . $photo1->file)}} 1024w" sizes="(max-width: 1500px) 100vw, 1500px" />
    <img width="367" height="304"   src="{{asset('uploads/' . $photo2->file)}}" class="ls-l" alt="" srcset="{{asset('uploads/' . $photo2->file)}} 367w,{{asset('uploads/' . $photo2->file)}}" sizes="(max-width: 367px) 100vw, 367px" style="top:618px;left:1292px;" data-ls="offsetxin:300;offsetyin:100;durationin:1500;easingin:easeOutQuint;rotatein:60;offsetxout:300;offsetyout:100;easingout:easeInQuint;rotateout:60;parallaxlevel:0;">
    <img width="724" height="820"   src="{{asset('uploads/' . $photo3->file)}}" class="ls-l" alt="" srcset="{{asset('uploads/' . $photo3->file)}} 724w,{{asset('uploads/' . $photo3->file)}} 265w" sizes="(max-width: 724px) 100vw, 724px" style="top:926px;left:-305px;" data-ls="offsetxin:-200;offsetyin:400;durationin:1500;delayin:500;easingin:easeOutQuint;rotatein:20;offsetxout:-200;offsetyout:400;easingout:easeInQuint;rotateout:20;parallaxlevel:0;">
    <img width="89" height="166"    src="{{asset('uploads/' . $photo4->file)}}" class="ls-l" alt="" style="top:636px;left:271px;" data-ls="offsetxin:-600;offsetyin:-150;durationin:2500;delayin:300;easingin:easeOutQuint;offsetxout:-200;offsetyout:-50;easingout:easeInQuint;parallaxlevel:0;">
    <img width="83" height="179"    src="{{asset('uploads/' . $photo5->file)}}" class="ls-l" alt="" style="top:1185px;left:1045px;" data-ls="offsetxin:400;offsetyin:-100;durationin:3500;delayin:500;easingin:easeOutQuint;offsetxout:400;offsetyout:-100;easingout:easeInQuint;parallaxlevel:0;">
    <img width="404" height="346"   src="{{asset('uploads/' . $photo6->file)}}" class="ls-l" alt="" srcset="{{asset('uploads/' . $photo6->file)}} 404w, {{asset('uploads/' . $photo6->file)}} 300w" sizes="(max-width: 404px) 100vw, 404px" style="top:1201px;left:547px;" data-ls="offsetxin:100;offsetyin:300;durationin:1200;delayin:200;easingin:easeOutQuint;rotatein:100;offsetxout:100;offsetyout:300;easingout:easeInQuint;rotateout:100;parallaxlevel:0;">
    <img width="404" height="346"   src="{{asset('uploads/' . $photo7->file)}}" class="ls-l" alt="" srcset="{{asset('uploads/' . $photo7->file)}} 404w,{{asset('uploads/' . $photo7->file)}} 300w" sizes="(max-width: 404px) 100vw, 404px" style="top:1107px;left:328px;" data-ls="offsetxin:-100;offsetyin:200;durationin:1100;delayin:300;easingin:easeOutQuint;rotatein:-100;offsetxout:-100;offsetyout:200;easingout:easeInQuint;rotateout:-100;parallaxlevel:0;">
    <p style="text-shadow: 0 10px 15px rgba(0,0,0,.4);white-space: normal;left:545px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:true;opacity:1;font-family:Nunito;color:#dde0e6;font-size:56px;padding-right:0px;top:149px;" class="ls-l" data-ls="showinfo:1;offsetyin:100lh;durationin:1500;delayin:500;clipin:0 0 100% 0;offsetyout:-200lh;">Under the hood</p>
    <div style="box-shadow: 0 20px 50px rgba(0,0,0,.5);top:224px;left:577px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;width:333px;height:69px;font-size:11px;" class="ls-l" data-ls="showinfo:1;durationin:750;delayin:1500;easingin:easeInOutQuad;"></div>
    <p style="border-top-right-radius: 5px; border-bottom-right-radius: 5px;top:223px;left:801px;text-align:initial;font-weight:600;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:36px;color:#ffffff;width:70px;padding-right:20px;padding-left:20px;background:#f07400;height:70px;line-height:70px;" class="ls-l" data-ls="showinfo:1;durationin:750;delayin:1500;easingin:easeOutQuint;rotateyin:90;transformoriginin:0% 50% 0;scalexout:.5;scaleyout:0;transformoriginout:-80% 0% 0;">API</p>
    <p style="border-top-left-radius: 5px; border-bottom-left-radius: 5px;top:223px;left:577px;text-align:right;font-weight:600;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:36px;color:#ffffff;width:184px;padding-right:20px;padding-left:20px;background:#0092bc;height:70px;line-height:70px;" class="ls-l" data-ls="showinfo:1;durationin:750;delayin:1500;easingin:easeOutQuint;rotateyin:-90;transformoriginin:100% 50% 0;scalexout:.5;scaleyout:0;transformoriginout:0% 0% 0;">LayerSlider</p>
    <img width="544" height="755" src="{{asset('uploads/' . $photo8->file)}}" class="ls-l" alt="" srcset="{{asset('uploads/' . $photo8->file)}} 544w, {{asset('uploads/' . $photo8->file)}} 216w" sizes="(max-width: 544px) 100vw, 544px" style="top:415px;left:437px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;" data-ls="showinfo:1;offsetxin:100;offsetyin:-300;durationin:1500;delayin:100;easingin:easeOutQuart;rotatein:30;offsetxout:100;offsetyout:-300;easingout:easeInQuart;rotateout:30;rotation:-6;">
    <img width="443" height="589" src="{{asset('uploads/' . $photo9->file)}}" class="ls-l" alt="" srcset="{{asset('uploads/' . $photo9->file)}} 443w, {{asset('uploads/' . $photo9->file)}} 226w" sizes="(max-width: 443px) 100vw, 443px" style="top:486px;left:484px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;" data-ls="showinfo:1;durationin:500;delayin:1500;rotatein:-6;scaleyin:0;offsetxout:100;offsetyout:-300;easingout:easeInQuart;rotateout:30;rotation:-6;">
    <p style="white-space: normal;left:498px;text-align:left;font-weight:400;font-style:normal;text-decoration:none;wordwrap:true;opacity:1;font-family:Nunito;color:#262d33;font-size:32px;top:538px;width:410px;" class="ls-l" data-ls="showinfo:1;durationin:1500;delayin:2000;easingin:easeOutQuint;rotatein:-6;scalexin:.9;scaleyin:.9;clipin:0;offsetxout:100;offsetyout:-300;easingout:easeInQuart;rotateout:30;rotation:-6.2;">Build from the simplest to the most advanced sliders with advanced features! For example:</p>
    <a style="" class="ls-l" href="#reverse-replay" target="_self" data-ls="showinfo:1;durationin:1500;delayin:2300;easingin:easeOutQuint;rotatein:-6;scalexin:.9;scaleyin:.9;clipin:0;offsetxout:100;offsetyout:-300;easingout:easeInQuart;rotateout:30;hover:true;hoverdurationin:250;hovereasingin:easeInOutQuad;hoveropacity:1;hoverbgcolor:#0092bc;hovercolor:#ffffff;rotation:-6.2;">
        <p style="border: 3px solid #0092bc; cursor: pointer;top:772px;left:542px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:24px;border-radius:50px;padding-top:10px;padding-bottom:10px;padding-right:40px;padding-left:40px;style:border: 3px solid rgba(255,255,255,.9);;color:#0092bc;" class="">REVERSE THIS SLIDE</p>
    </a><img width="523" height="453" src="{{asset('uploads/' . $photo10->file)}}" class="ls-l" alt="" srcset="{{asset('uploads/' . $photo10->file)}} 523w, {{asset('uploads/' . $photo10->file)}}300w" sizes="(max-width: 523px) 100vw, 523px" style="top:1240px;left:1151px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;" data-ls="showinfo:1;offsetyin:100;durationin:1800;delayin:500;easingin:easeOutQuint;rotatein:-10;offsetyout:100;easingout:easeInQuint;rotateout:-10;">
    <img width="551" height="495" src="{{asset('uploads/' . $photo11->file)}}" class="ls-l" alt="" srcset="{{asset('uploads/' . $photo11->file)}} 551w, {{asset('uploads/' . $photo11->file)}} 300w" sizes="(max-width: 551px) 100vw, 551px" style="top:183px;left:-191px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;" data-ls="showinfo:1;offsetxin:-200;offsetyin:-75;durationin:1500;delayin:150;easingin:easeOutQuint;rotatein:30;offsetxout:-200;offsetyout:-75;easingout:easeInQuint;rotateout:30;">
    <a style="" class="ls-l" href="#reverse-replay" target="_self" data-ls="showinfo:1;transitionin:false;offsetxout:100;offsetyout:-300;easingout:easeInQuart;rotateout:30;texttransitionin:true;texttypein:chars_asc;textshiftin:30;textdurationin:1500;textstartatin:transitioninend + 2600;loop:true;loopduration:150;loopeasing:easeInQuint;loopscalex:1.4;loopscaley:1.4;loopcount:1;loopyoyo:true;rotation:-16;">
        <p style="cursor: pointer;top:868px;left:622px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;color:#0092bc;font-family:Pacifico;font-size:64px;" class="">Try it!</p>
    </a>
    <a style="" class="ls-l" href="#next" target="_self" data-ls="showinfo:1;durationin:500;delayin:4000;rotatexin:60;scalexin:.8;scaleyin:.8;rotatexout:60;scalexout:.8;scaleyout:.8;loop:true;loopoffsetx:15;loopduration:800;loopeasing:easeInQuint;loopcount:-1;loopyoyo:true;hover:true;hoveropacity:1;hoverscalex:1.05;hoverscaley:1.05;">
        <p style="top:1009px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;font-family:Nunito;font-size:36px;color:#ffffff;background:#f07400;padding-top:10px;padding-bottom:10px;padding-right:40px;padding-left:40px;left:1192px;border-radius:50px;" class="">CONTINUE</p>
    </a><img width="353" height="439" src="{{asset('uploads/' . $photo12->file)}}" class="ls-l" alt="" srcset="{{asset('uploads/' . $photo12->file)}} 353w, {{asset('uploads/' . $photo12->file)}} 241w" sizes="(max-width: 353px) 100vw, 353px" style="top:279px;left:943px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;" data-ls="showinfo:1;durationin:3500;easingin:easeOutQuint;rotatein:60;transformoriginin:400% 100% 0;offsetxout:right;durationout:500;startatout:loopend + 0;easingout:linear;transformoriginout:200% 75% 0;loop:true;loopduration:1500;loopstartat:transitioninend - 500;loopeasing:easeInQuad;looprotate:-110;looptransformorigin:200% 75% 0;loopcount:1;">
    <img width="185" height="349" src="{{asset('uploads/' . $photo13->file)}}" class="ls-l" alt="" srcset="{{asset('uploads/' . $photo13->file)}} 185w, {{asset('uploads/' . $photo13->file)}} 159w" sizes="(max-width: 185px) 100vw, 185px" style="top:636px;left:19px;text-align:initial;font-weight:400;font-style:normal;text-decoration:none;wordwrap:false;opacity:1;" data-ls="showinfo:1;offsetxin:-200;offsetyin:-100;delayin:600;easingin:easeOutQuad;rotatein:20;">
`
@endif
</div>